config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#index'
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#login'
  post 'logout', to: 'sessions#logout'

  resources :users, only: [:new, :create, :show]
  resources :jots, except: [:index] do
    resources :votes, only: [:create, :destroy]
  end
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.sample
    all.sample
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tags, dependent: :destroy
  has_many :jots, through: :tags

  validates :name, :priority, presence: true
  validates :name, :priority, uniqueness: true

  def top_jot
    jots.joins(:votes).order('votes desc').limit(1)[0] or jots.last
  end
end

app/models/jot.rb
class Jot < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_one_attached :image
  has_many :tags, dependent: :destroy
  has_many :categories, through: :tags
  has_many :votes, dependent: :destroy

  validates :title, :text, :image, :categories, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :jot
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_many :jots, foreign_key: :author_id, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :name, :username, presence: true
  validates :username, uniqueness: true
  validates :username, format: { with: /\A[a-zA-Z0-9]+\Z/, message: 'must not contain spaces' }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :jot

  validates :user_id, uniqueness: { scope: :jot_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  before_action :require_login!, only: [:index]

  def index
    @latest_jot = Jot.last
    @top_categories = Category.all.order(:priority).limit(4)
    render 'layouts/index'
  end

  private

  def require_login!
    redirect_to login_path, alert: 'Log in to continue' unless user_signed_in?
  end

  def require_logout!
    redirect_back(fallback_location: root_path, notice: "You're already logged in") if user_signed_in?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login!
  before_action :set_category, only: %i[show edit update destroy]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'New category added successfully'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to root_path, notice: 'Category deleted successfully'
  end

  private

  def category_params
    params.require(:category).permit(:name, :priority)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/jots_controller.rb
class JotsController < ApplicationController
  before_action :require_login!
  before_action :set_jot, only: %i[show edit update destroy]
  before_action :author?, only: %i[edit update destroy]
  before_action :set_categories, only: %i[new create edit]

  def new
    @jot = Jot.new
  end

  def create
    @jot = current_user.jots.build(jot_params)

    if @jot.save
      redirect_to jot_path(@jot), notice: 'Jot created successfully'
    else
      render action: :new
    end
  end

  def show; end

  def edit; end

  def update
    if @jot.update(jot_params)
      redirect_to @jot, notice: 'Jot successfully updated'
    else
      render action: :edit
    end
  end

  def destroy
    @jot.destroy
    redirect_to root_path, notice: 'Jot deleted successfully'
  end

  private

  def author?
    return if @jot.author == current_user

    redirect_back(fallback_location: root_path, alert: 'Unauthorized')
  end

  def set_jot
    @jot = Jot.find(params[:id])
  end

  def set_categories
    @categories = Category.all
  end

  def jot_params
    params.require(:jot).permit(:title, :text, :image, category_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logout!, only: [:login]
  before_action :require_login!, only: [:logout]

  def new; end

  def login
    case request.method
    when 'GET'
      render :login
    when 'POST'
      if !session_params[:username].empty? and (user = User.find_by(username: session_params[:username]))
        session[:user_id] = user.id
        redirect_to root_path, notice: 'Signed in successfully'
      else
        flash.now[:alert] = 'User with username not found'
        render :login
      end
    end
  end

  def logout
    session.clear
    flash[:notice] = 'Signed out successfully'
    redirect_to login_path
  end

  private

  def session_params
    params.permit(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login!, only: [:show]
  before_action :require_logout!, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Jot Leaf, #{@user.username}"
      redirect_to root_path
    else
      render action: :new
    end
  end

  def show; end

  private

  def user_params
    params.require(:user).permit(:name, :username)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :require_login!

  def create
    vote = current_user.votes.build(vote_params)
    redirect_to jot_path(vote.jot), notice: 'Voted' if vote.save
  end

  def destroy
    vote = Vote.find(params[:id])
    vote.destroy
    redirect_to jot_path(params[:jot_id]), alert: 'Unvoted'
  end

  private

  def vote_params
    params.permit(:jot_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_signed_in?
    session[:user_id] ? true : false
  end

  def current_user
    user_signed_in? ? User.find(session[:user_id]) : nil
  end

  def flash_class
    return 'success' if flash[:notice]
    return 'danger' if flash[:alert]
  end

  def flash_message
    render 'layouts/flash_message' if flash.present?
  end

  def categories
    @categories = Category.all
  end

  def active_class(category)
    return 'active' if request.path == category_path(category)
  end
end

app/helpers/jots_helper.rb
module JotsHelper
  def new_jot_button
    blind_paths = [
      login_path, new_user_path,
      new_jot_path
    ]
    return if blind_paths.include?(request.path)

    render 'layouts/new_jot_button'
  end

  def author_controls(jot)
    render 'author_controls' if author?(jot)
  end

  def latest_jot(jot)
    render 'layouts/latest_jot_card' if jot
  end

  def top_jot(category)
    render 'layouts/top_jot_card', category: category if category.top_jot
  end

  def jot_image(jot, css_class: '')
    image_tag jot.image, alt: jot.title, class: css_class if jot.image.attached?
  end

  def desktop_ordering(index)
    return 'order-md-first' unless odd_rows.include?(index + 1)
  end

  def mobile_ordering(index)
    css_class = []
    css_class << 'order-last' unless index.even?
    css_class << 'order-md-first' if odd_rows.include?(index + 1)
    css_class.join(' ')
  end

  def odd_rows
    pattern = [1, 2]

    while pattern.last <= 100
      pattern << pattern.last + 3
      pattern << pattern.last + 1
    end
    pattern
  end

  private

  def author?(jot)
    jot.author == current_user
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def session_controls
    if user_signed_in?
      link_to 'LOGOUT', logout_path, method: :post, class: 'nav-link text-danger'
    else
      link_to 'LOGIN', login_path, class: 'nav-link'
    end
  end

  def user_controls
    if user_signed_in?
      link_to "@#{current_user.username}", user_path(current_user), class: 'nav-link'
    else
      link_to 'REGISTER', new_user_path, class: 'nav-link'
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def vote_button(jot)
    vote = Vote.find_by(jot: jot, user: current_user)

    if vote
      link_to('Unvote', jot_vote_path(jot, vote), method: :delete, class: 'btn btn-warning ms-auto fw-bold')
    else
      link_to('Vote', jot_votes_path(jot), method: :post, class: 'btn btn-primary ms-auto fw-bold')
    end
  end
end

app/views/categories/_form.html.erb
<%= form_with model: @category, local: true, class: 'py-5' do |form| %>
  <% @category.errors.full_messages.each do |err_msg| %>
    <div class="alert bg-danger text-light py-1 mb-1 fs-xs lh-sm"><%= err_msg %></div>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name, class: 'form-control border-primary', placeholder: 'Name of category' %>

  <%= form.label :priority %>
  <%= form.number_field :priority, class: 'form-control border-primary', placeholder: 'Priority' %>

  <%= form.submit 'Save', class: 'btn btn-primary px-5 fw-bold mt-3' %>
<% end %>

app/views/categories/edit.html.erb
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-sm-10 col-md-5 col-lg-4">
      <div class="card alert-primary border-0">
        <div class="card-body">
          <h1 class="card-title fw-bold fs-5 mb-0">Edit <%= @category.name %></h1>
          <%= render 'form' %>

          <%= link_to category_path(@category), method: :delete, data: { confirm: 'Delete' }, class: 'btn btn-light border-danger d-inline-flex p-1 rounded-circle' do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="1.3rem" height="1.3rem" fill="currentColor" class="bi bi-trash text-danger" viewBox="0 0 16 16">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
              <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
            </svg>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-sm-10 col-md-5 col-lg-4">
      <div class="card alert-primary border-0">
        <div class="card-body">
          <h1 class="card-title fw-bold fs-5 mb-0">Add new category</h1>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container-lg  px-0 px-lg-3 overflow-x-hidden">
  <!-- Magazine -->
  <div class="row g-0">
    <% @category.jots.includes(image_attachment: :blob).each_with_index do |jot, index| %>
      <div class="col-12 col-md-6">
        <%= render 'jots/card', jot: jot, index: index %>
      </div>
    <% end %>
  </div>
</div>

app/views/jots/_author_controls.html.erb
<%= link_to jot_path(@jot), method: :delete, data: { confirm: 'Delete' }, class: 'btn btn-light d-inline-flex p-1 rounded-circle' do %>
  <svg xmlns="http://www.w3.org/2000/svg" width="1.3rem" height="1.3rem" fill="currentColor" class="bi bi-trash text-danger" viewBox="0 0 16 16">
    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
  </svg>
<% end %>
<%= link_to edit_jot_path(@jot), class: 'btn btn-light d-inline-flex p-1 mx-1 rounded-circle' do %>
<svg xmlns="http://www.w3.org/2000/svg" width="1.3rem" height="1.3rem" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
  <path d="M13.498.795l.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
</svg>
<% end %>

app/views/jots/_card.html.erb
<div class="card jot-card h-100 rounded-0 border-0">
  <div class="row g-0 h-100">
    <div class="col-6 <%= mobile_ordering(index) %> position-relative img-overlay">
      <%= jot_image jot, css_class: 'card-img h-100 object-fit-cover rounded-0' %>
    </div>
    <div class="col-6 <%= desktop_ordering(index) %>">
      <div class="card-body h-100">
        <h5 class="d-inline text-primary border-bottom border-2 border-primary">
          <%= @category.name %>
        </h5>
        <h6 class="fw-bold mt-1"><%= jot.title %></h6>
        <p class="lh-1 fw-light"><%= jot.text.slice(..200) %>...</p>
        <%= link_to 'Read more', jot_path(jot), class: 'text-decoration-none' %>
      </div>
    </div>
  </div>
</div>

app/views/jots/_form.html.erb
<%= form_with(model: @jot, local: true) do |form| %>
  <% @jot.errors.full_messages.each do |err_msg| %>
    <div class="alert bg-danger text-light py-1 mb-1 fs-xs lh-sm"><%= err_msg %></div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: 'fw-bold' %>
    <%= form.text_field :title, class: 'form-control border-primary' %>
  </div>

  <div class="mb-3">
    <%= form.label :text, class: 'fw-bold' %>
    <%= form.text_area :text, rows: 5,  class: 'form-control border-primary' %>
  </div>

  <div class="mb-3" id="jot-categories">
    <p class="mb-0"><b>Categories:</b></p>
    <%= form.collection_check_boxes :category_ids, (@categories), :id, :name do |cb| %>
      <div class="d-inline-flex px-3 py-1 mb-1 bg-secondary rounded-pill">
        <%= cb.label(class: 'form-check-label text-primary me-1') %>
        <%= cb.check_box(class: 'form-check-input rounded-circle border-0') %>
      </div>
    <% end %>
  </div>

  <div class="my-3">
    <%= form.label :image, class: 'fw-bold' %>
    <%= form.file_field :image, direct_upload: true, class: 'form-control border-primary' %>
  </div>

  <div class="">
    <%= form.submit 'Publish', class: 'btn btn-primary fw-bold px-5' %>
  </div>
<% end %>

app/views/jots/edit.html.erb
<div class="container-lg py-5">
  <div class="row align-items-center justify-content-center">
    <div class="col-sm-8 col-md-7 col-lg-6">
      <h1 class="fs-2 d-inline-block text-primary mb-4 px-5 alert-primary rounded-pill">
        Edit jot
      </h1>

      <div class="card alert-primary border-primary">
        <div class="card-body py-5">
          <%= render 'form' %>
        </div>
      </div>
    </div>
    <div class="col-auto d-flex">
      <div class="p-3 shadow bg-primary border border-primary ms-md-5" id="jot-pen-icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="5rem" height="5rem" fill="currentColor" class="bi bi-vector-pen text-white" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M10.646.646a.5.5 0 0 1 .708 0l4 4a.5.5 0 0 1 0 .708l-1.902 1.902-.829 3.313a1.5 1.5 0 0 1-1.024 1.073L1.254 14.746 4.358 4.4A1.5 1.5 0 0 1 5.43 3.377l3.313-.828L10.646.646zm-1.8 2.908l-3.173.793a.5.5 0 0 0-.358.342l-2.57 8.565 8.567-2.57a.5.5 0 0 0 .34-.357l.794-3.174-3.6-3.6z"/>
          <path fill-rule="evenodd" d="M2.832 13.228L8 9a1 1 0 1 0-1-1l-4.228 5.168-.026.086.086-.026z"/>
        </svg>
      </div>
    </div>
  </div>
</div>

app/views/jots/new.html.erb
<div class="container-lg py-5">
  <div class="row align-items-center justify-content-center">
    <div class="col-sm-8 col-md-7 col-lg-6">
      <h1 class="fs-2 d-inline-block text-primary mb-4 px-5 alert-primary rounded-pill">
        Jot it down
      </h1>

      <div class="card alert-primary border-primary">
        <div class="card-body py-5">
          <%= render 'form' %>
        </div>
      </div>
    </div>
    <div class="col-auto d-flex">
      <div class="p-3 shadow bg-primary border border-primary ms-md-5" id="jot-pen-icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="5rem" height="5rem" fill="currentColor" class="bi bi-vector-pen text-white" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M10.646.646a.5.5 0 0 1 .708 0l4 4a.5.5 0 0 1 0 .708l-1.902 1.902-.829 3.313a1.5 1.5 0 0 1-1.024 1.073L1.254 14.746 4.358 4.4A1.5 1.5 0 0 1 5.43 3.377l3.313-.828L10.646.646zm-1.8 2.908l-3.173.793a.5.5 0 0 0-.358.342l-2.57 8.565 8.567-2.57a.5.5 0 0 0 .34-.357l.794-3.174-3.6-3.6z"/>
          <path fill-rule="evenodd" d="M2.832 13.228L8 9a1 1 0 1 0-1-1l-4.228 5.168-.026.086.086-.026z"/>
        </svg>
      </div>
    </div>
  </div>
</div>

app/views/jots/show.html.erb
<div class="container-lg py-5">
  <div class="row gx-lg-1 justify-content-center align-items-end">
    <div class="col-md-5 mb-4 mb-md-0">
      <h1 class="fs-2 mb-3 text-primary lh-1"><%= @jot.title %></h1>
      <ul class="list-group list-group-flush">
        <li class="list-group-item px-0 bg-transparent">
          <p class="text-primary fs-sm mb-0">
            <i class="fw-bold">Author:</i> <span class="text-white"><%= @jot.author.name %></span>
            | <i class="fw-bold">Published on:</i> <span class="text-white"><%= @jot.created_at.to_date %></span>
            | <span class="fw-bold me-1">Votes:</span> <span class="text-white"><%= @jot.votes.count %></span>
          </p>
        </li>
        <li class="list-group-item px-0 bg-transparent">
          <% @jot.categories.each do |c| %>
            <%= link_to c.name, category_path(c), class: 'd-inline-flex mb-1 px-3 bg-light text-secondary text-decoration-none rounded-pill' %>
          <% end %>
        </li>
        <li class="list-group-item px-0 align-items-center d-flex bg-transparent">
          <%= author_controls(@jot) %>
          <%= vote_button(@jot) %>
        </li>
      </ul>
      <%= jot_image @jot, css_class: 'jot-image object-fit-cover rounded' %>
    </div>

    <div class="col-md-1 h-100 mb-4 mb-md-0">
      <div class="d-flex flex-md-column bg-light px-1"></div>
    </div>

    <div class="col-md-7 col-lg-6">
      <div class="jot-text-wrapper alert-primary rounded p-3">
        <%= simple_format @jot.text, class: 'text-secondary fw-light lh-sm' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash_message.html.erb
<div class="d-flex">
  <div class="alert border-2 text-white border-white shadow-sm bg-<%= flash_class %> alert-dismissible rounded-end position-fixed d-inline-flex py-2 mt-1 fade show" role="alert" id="main-alert">
    <p class="mb-0"><%= flash[:notice] %></p>
    <p class="mb-0"><%= flash[:alert] %></p>
    <button type="button" class="btn-close bg-white fs-xs p-1 mt-2 me-2" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="mt-auto">
  <div class="container-lg py-4 py-md-2">
    <div class="row g-0 justify-content-md-between align-items-center">
      <div class="col-12 col-md-2 mb-3 mb-md-0">
        <%= link_to root_path, class: 'navbar-brand p-0 me-0' do %>
          <%= image_tag asset_path('logo_white.png', alt: 'Jot Leaf') %>
        <% end %>
      </div>

      <div class="col-12 col-md-auto mb-3 mb-md-0 text-md-end text-lg-center fs-sm fw-light">
        <%= link_to 'Privacy Policy', '#', class: 'text-decoration-none me-1' %>
        <%= link_to 'Terms & Conditions', '#', class: 'text-decoration-none me-1' %>
        <p class="mb-0 d-md-inline text-white">&copy;2021. All rights reserved</p>
      </div>

      <div class="col-12 col-md-auto">
        <nav class="nav align-items-center justify-content-md-end">
          <p class="mb-0 d-inline text-white me-1">Connect with us:</p>
          <%= link_to '#', class: 'nav-link d-inline-flex align-items-center bg-primary rounded-circle p-2' do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="1.2rem" height="1.2rem" fill="currentColor" class="bi bi-facebook text-secondary" viewBox="0 0 16 16">
              <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
            </svg>
          <% end %>
          <%= link_to '#', class: 'nav-link d-inline-flex align-items-center bg-primary rounded-circle p-2 mx-1' do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="1.2rem" height="1.2rem" fill="currentColor" class="bi bi-twitter text-secondary" viewBox="0 0 16 16">
              <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
            </svg>
          <% end %>
          <%= link_to '#', class: 'nav-link d-inline-flex align-items-center bg-primary rounded-circle p-2' do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="1.2rem" height="1.2rem" fill="currentColor" class="bi bi-instagram text-secondary" viewBox="0 0 16 16">
              <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
            </svg>
          <% end %>
        </nav>
      </div>
    </div>
  </div>
</footer>

app/views/users/show.html.erb
<div class="container-lg py-5">
  <h1 class="fs-5"><%= current_user.name %></h1>
</div>